In [39]:
from tensorflow.keras.preprocessing.text import one_hot

In [40]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [41]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [42]:
## vocabulary size

voc_size = 10000

In [43]:
## one - hot representation

one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1742, 6228, 2165, 5737],
 [1742, 6228, 2165, 5637],
 [1742, 5123, 2165, 9306],
 [3847, 7217, 8183, 1954, 6170],
 [3847, 7217, 8183, 1954, 7075],
 [2826, 1742, 8501, 2165, 5211],
 [6283, 3469, 2948, 1954]]

In [44]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

In [45]:
import numpy as np

In [46]:
## making all sentences of same size

sent_lenth = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_lenth)
print(embedded_docs)

[[   0    0    0    0 1742 6228 2165 5737]
 [   0    0    0    0 1742 6228 2165 5637]
 [   0    0    0    0 1742 5123 2165 9306]
 [   0    0    0 3847 7217 8183 1954 6170]
 [   0    0    0 3847 7217 8183 1954 7075]
 [   0    0    0 2826 1742 8501 2165 5211]
 [   0    0    0    0 6283 3469 2948 1954]]


In [47]:
## feature representation (dimensions)

dim = 10


In [48]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_lenth))
model.compile('adam','mse')

c:\Users\HP\OneDrive\Desktop\WEB D\Projects\ANN project\my_env\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [50]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [54]:
embedded_predicted = model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [55]:
print(embedded_docs[0])
print(embedded_predicted[0][0])

[   0    0    0    0 1742 6228 2165 5737]
[ 0.03573581 -0.01927263 -0.03309915  0.03075845  0.01774777 -0.03875866
  0.02662135 -0.00604696 -0.03072672 -0.02414507]
